import { ItemType, RPGSet, Rarity, RPGItem } from "./types";

export const BASE_PROMPT = "Fantasy RPG game item illustration, 2D digital art, isolated on pure transparent background, no background, no floor, no shadow beneath, centered composition, detailed texture, dark fantasy medieval aesthetic, dramatic lighting with subtle inner glow, game asset style similar to Diablo or Path of Exile, high contrast, ultra detailed.";

export const BOOTS_POSE = "Both boots shown as a pair, left and right boot side by side, toes pointing diagonally forward and outward, slight 3/4 perspective view, symmetrical composition.";

export const GLOVES_POSE = "Both gloves shown as a complete pair arranged in an X formation, fingers pointing downward, palms facing viewer, overlapping at the wrists to form the X shape, symmetrical composition centered in frame.";

export const PANTS_POSE = "Medieval RPG legwear, high-waisted trousers or layered leg armor, loose-fitting fabric with cinched ankles or ornate plate greaves, fantasy medieval aesthetic, NO modern military details, NO cargo pockets, NO camouflage, showing waist to ankle, NO BOOTS, legs end at the ankles.";

export const AMULET_POSE = "Complete amulet shown centered, including the full pendant and the entire circular cord or chain, no parts of the cord are cut off by the frame, the entire necklace loop is visible and contained within the image boundaries.";

export const QUIVER_POSE = "A medieval leather quiver filled with several arrows, shown from a side or 3/4 perspective, ornate carvings or metal reinforcements, arrows have feathered fletching, centered composition.";

export const CLASS_CONFIGS: Record<string, { name: string; theme: string; color: string; accentColor: string }> = {
  Warrior: { name: "Guerreiro", theme: "Aço negro com detalhes dourados, estilo cavaleiro imperial", color: "#06090f", accentColor: "#c9a84c" },
  Mage: { name: "Mago", theme: "Roxo escuro com runas prateadas e cristais brilhantes", color: "#1a0a2e", accentColor: "#c0c0c0" },
  Hunter: { name: "Hunter (Elfo)", theme: "Couro negro com detalhes esmeralda, estilo ranger furtivo", color: "#1a3a1a", accentColor: "#50c878" },
  Lord: { name: "Lord Vassalo", theme: "Ouro real com veludo carmesim, estilo realeza e liderança", color: "#2d0a0a", accentColor: "#ffd700" },
  Assassin: { name: "Assassino", theme: "Couro negro com detalhes carmesim, estilo furtivo e letal", color: "#0a0a0a", accentColor: "#ff0000" },
};

export const ITEMS_BY_CLASS: Record<string, Record<string, RPGItem[]>> = {
  Warrior: {
    Common: [
      { id: "w-c-helm", name: "Elmo de Ferro Simples", type: ItemType.HELMET, rarity: Rarity.COMMON, prompt: `${BASE_PROMPT} A simple open-faced iron helmet, basic design.` },
      { id: "w-c-armor", name: "Peitoral de Couro", type: ItemType.ARMOR, rarity: Rarity.COMMON, prompt: `${BASE_PROMPT} A basic brown leather chestpiece, worn edges.` },
      { id: "w-c-pants", name: "Calças de Malha Simples", type: ItemType.PANTS, rarity: Rarity.COMMON, prompt: `${BASE_PROMPT} ${PANTS_POSE} Simple grey fabric trousers with reinforced knees.` },
      { id: "w-c-gloves", name: "Luvas de Couro", type: ItemType.GLOVES, rarity: Rarity.COMMON, prompt: `${BASE_PROMPT} ${GLOVES_POSE} Basic brown leather gloves, simple stitching.` },
      { id: "w-c-boots", name: "Botas de Couro", type: ItemType.BOOTS, rarity: Rarity.COMMON, prompt: `${BASE_PROMPT} ${BOOTS_POSE} Simple brown leather boots, worn soles.` },
      { id: "w-c-ring", name: "Anel de Bronze", type: ItemType.RING, rarity: Rarity.COMMON, prompt: `${BASE_PROMPT} A plain bronze band, slightly tarnished.` },
      { id: "w-c-amulet", name: "Amuleto de Pedra", type: ItemType.AMULET, rarity: Rarity.COMMON, prompt: `${BASE_PROMPT} ${AMULET_POSE} A smooth river stone on a simple leather cord.` },
      { id: "w-c-sword", name: "Espada Curta de Ferro", type: ItemType.WEAPON, rarity: Rarity.COMMON, prompt: `${BASE_PROMPT} A simple iron shortsword, plain hilt, basic craftsmanship.` },
      { id: "w-c-shield", name: "Escudo de Madeira", type: ItemType.OFFHAND, rarity: Rarity.COMMON, prompt: `${BASE_PROMPT} A round wooden shield with iron rim, simple leather straps.` },
    ],
    Intermediate: [
      { id: "w-i-helm", name: "Elmo de Aço", type: ItemType.HELMET, rarity: Rarity.INTERMEDIATE, prompt: `${BASE_PROMPT} A sturdy steel helmet with a nose guard, polished finish.` },
      { id: "w-i-armor", name: "Cota de Malha", type: ItemType.ARMOR, rarity: Rarity.INTERMEDIATE, prompt: `${BASE_PROMPT} A steel chainmail hauberk, interlocking rings.` },
      { id: "w-i-pants", name: "Calças de Couro Batido", type: ItemType.PANTS, rarity: Rarity.INTERMEDIATE, prompt: `${BASE_PROMPT} ${PANTS_POSE} Dark brown hardened leather trousers with metal studs.` },
      { id: "w-i-gloves", name: "Manoplas de Couro Reforçado", type: ItemType.GLOVES, rarity: Rarity.INTERMEDIATE, prompt: `${BASE_PROMPT} ${GLOVES_POSE} Hardened leather gloves with iron studs on knuckles.` },
      { id: "w-i-boots", name: "Botas de Couro e Ferro", type: ItemType.BOOTS, rarity: Rarity.INTERMEDIATE, prompt: `${BASE_PROMPT} ${BOOTS_POSE} Sturdy leather boots with iron toe caps and buckles.` },
      { id: "w-i-ring", name: "Anel de Ferro", type: ItemType.RING, rarity: Rarity.INTERMEDIATE, prompt: `${BASE_PROMPT} A thick iron ring with a simple engraved pattern.` },
      { id: "w-i-amulet", name: "Amuleto de Ferro", type: ItemType.AMULET, rarity: Rarity.INTERMEDIATE, prompt: `${BASE_PROMPT} ${AMULET_POSE} An iron pendant shaped like a shield on a sturdy chain.` },
      { id: "w-i-sword", name: "Espada Longa de Aço", type: ItemType.WEAPON, rarity: Rarity.INTERMEDIATE, prompt: `${BASE_PROMPT} A sharp steel longsword, polished blade, simple crossguard.` },
      { id: "w-i-shield", name: "Escudo de Ferro", type: ItemType.OFFHAND, rarity: Rarity.INTERMEDIATE, prompt: `${BASE_PROMPT} A heater shield made of iron plates, sturdy construction.` },
    ],
    Excellent: [
      { id: "w-ex-helm", name: "Elmo de Placas Polido", type: ItemType.HELMET, rarity: Rarity.EXCELLENT, prompt: `${BASE_PROMPT} A full-face steel helmet with a plume, highly polished.` },
      { id: "w-ex-armor", name: "Armadura de Placas", type: ItemType.ARMOR, rarity: Rarity.EXCELLENT, prompt: `${BASE_PROMPT} Full plate chest armor, polished steel with brass rivets.` },
      { id: "w-ex-pants", name: "Grevas de Placas", type: ItemType.PANTS, rarity: Rarity.EXCELLENT, prompt: `${BASE_PROMPT} ${PANTS_POSE} Polished steel plate leg armor, articulated joints.` },
      { id: "w-ex-gloves", name: "Manoplas de Placas", type: ItemType.GLOVES, rarity: Rarity.EXCELLENT, prompt: `${BASE_PROMPT} ${GLOVES_POSE} Polished steel gauntlets, articulated fingers, brass trim.` },
      { id: "w-ex-boots", name: "Botas de Placas", type: ItemType.BOOTS, rarity: Rarity.EXCELLENT, prompt: `${BASE_PROMPT} ${BOOTS_POSE} Polished steel sabatons, articulated plates, knightly style.` },
      { id: "w-ex-ring", name: "Anel de Prata", type: ItemType.RING, rarity: Rarity.EXCELLENT, prompt: `${BASE_PROMPT} A fine silver ring with a small blue sapphire.` },
      { id: "w-ex-amulet", name: "Amuleto de Prata", type: ItemType.AMULET, rarity: Rarity.EXCELLENT, prompt: `${BASE_PROMPT} ${AMULET_POSE} A silver medallion with an engraved lion crest on a silver chain.` },
      { id: "w-ex-sword", name: "Montante de Aço Temperado", type: ItemType.WEAPON, rarity: Rarity.EXCELLENT, prompt: `${BASE_PROMPT} A massive two-handed greatsword, blue-tinted steel, ornate hilt.` },
      { id: "w-ex-shield", name: "Escudo de Torre", type: ItemType.OFFHAND, rarity: Rarity.EXCELLENT, prompt: `${BASE_PROMPT} A large rectangular tower shield, reinforced with steel bands and spikes.` },
    ],
    Epic: [
      { id: "twilight-helm", name: "Elmo do Crepúsculo", type: ItemType.HELMET, rarity: Rarity.EPIC, prompt: `${BASE_PROMPT} Full face knight helmet, black steel with gold filigree trim, dark visor with orange ember glow from within, ornate crown-like crest on top, scratched battle-worn metal, dark gold runes engraved on cheeks, color palette: black #06090f, dark gold #c9a84c, ember orange.` },
      { id: "twilight-armor", name: "Armadura do Crepúsculo", type: ItemType.ARMOR, rarity: Rarity.EPIC, prompt: `${BASE_PROMPT} Heavy full plate chest armor, black tempered steel with gold trim on edges and pauldrons, engraved sun emblem on chest plate, battle-worn with subtle scratches, layered metal plates with dark leather straps, color palette: black #06090f, dark gold #c9a84c, deep iron grey.` },
      { id: "twilight-boots", name: "Botas do Crepúsculo", type: ItemType.BOOTS, rarity: Rarity.EPIC, prompt: `${BASE_PROMPT} ${BOOTS_POSE} Heavy knight sabatons, black steel boots with gold trim, articulated metal plates over dark leather, pointed toe cap with small gold ornament, battle-worn texture, color palette: black #06090f, dark gold #c9a84c.` },
      { id: "twilight-sword", name: "Espada do Crepúsculo", type: ItemType.WEAPON, rarity: Rarity.EPIC, prompt: `${BASE_PROMPT} Two-handed longsword, black steel blade with gold runes glowing along the fuller, ornate crossguard with twin dragon heads in gold, wrapped dark leather grip with gold wire binding, pommel shaped like a crown, faint orange magical aura along blade edge, color palette: black #06090f, dark gold #c9a84c, ember glow.` },
      { id: "twilight-shield", name: "Escudo do Crepúsculo", type: ItemType.OFFHAND, rarity: Rarity.EPIC, prompt: `${BASE_PROMPT} Large kite shield, black steel with gold embossed sun emblem at center, reinforced edges with gold trim, aged leather backing visible at corners, battle-scarred surface, subtle magical barrier shimmer, color palette: black #06090f, dark gold #c9a84c.` },
      { id: "twilight-amulet", name: "Amuleto do Crepúsculo", type: ItemType.AMULET, rarity: Rarity.EPIC, prompt: `${BASE_PROMPT} ${AMULET_POSE} Ornate pendant amulet on a dark chain, black steel frame with a glowing amber gemstone at center, gold filigree surrounding the gem in a sun pattern, warm orange magical glow emanating from gem, intricate engravings on the frame, color palette: black #06090f, dark gold #c9a84c, amber gemstone.` },
      { id: "twilight-ring", name: "Anel do Crepúsculo", type: ItemType.RING, rarity: Rarity.EPIC, prompt: `${BASE_PROMPT} Heavy signet ring, black steel band with a flat top bearing an engraved crown emblem, small amber gemstone inlaid beside the emblem, thick warrior's ring with worn edges, subtle gold highlights on engraving, color palette: black #06090f, dark gold #c9a84c, amber.` },
      { id: "twilight-gloves", name: "Manoplas do Crepúsculo", type: ItemType.GLOVES, rarity: Rarity.EPIC, prompt: `${BASE_PROMPT} ${GLOVES_POSE} Heavy knight gauntlets, black steel plates over dark leather, gold trim on knuckle guards, articulated finger plates, battle-worn with scratches, color palette: black #06090f, dark gold #c9a84c.` },
      { id: "twilight-pants", name: "Calças do Crepúsculo", type: ItemType.PANTS, rarity: Rarity.EPIC, prompt: `${BASE_PROMPT} ${PANTS_POSE} Heavy leg armor, black steel plates over dark leather, gold trim on knee guards and thighs, articulated metal plates, battle-worn with scratches, color palette: black #06090f, dark gold #c9a84c.` },
    ],
    Legendary: [
      { id: "w-l-helm", name: "Elmo do Rei Titã", type: ItemType.HELMET, rarity: Rarity.LEGENDARY, prompt: `${BASE_PROMPT} A colossal helmet made of ancient mountain stone and adamantine, glowing blue core, divine aura.` },
      { id: "w-l-armor", name: "Couraça do Titã", type: ItemType.ARMOR, rarity: Rarity.LEGENDARY, prompt: `${BASE_PROMPT} Colossal chest armor made of ancient mountain stone and adamantine, glowing blue core at center.` },
      { id: "w-l-boots", name: "Passos do Colosso", type: ItemType.BOOTS, rarity: Rarity.LEGENDARY, prompt: `${BASE_PROMPT} ${BOOTS_POSE} Massive stone and metal boots, glowing runes of strength, earthquake cracks.` },
      { id: "w-l-sword", name: "Destruidora de Mundos", type: ItemType.WEAPON, rarity: Rarity.LEGENDARY, prompt: `${BASE_PROMPT} A legendary colossal sword, blade made of obsidian and lava, glowing cracks, hilt made of dragon bone, intense heat waves.` },
      { id: "w-l-shield", name: "Égide Divina", type: ItemType.OFFHAND, rarity: Rarity.LEGENDARY, prompt: `${BASE_PROMPT} A shield made of pure celestial light and gold, floating wings on sides, blinding radiance.` },
      { id: "w-l-amulet", name: "Coração do Vulcão", type: ItemType.AMULET, rarity: Rarity.LEGENDARY, prompt: `${BASE_PROMPT} ${AMULET_POSE} A pendant made of a pulsing lava core encased in obsidian, glowing with intense heat.` },
      { id: "w-l-ring", name: "Anel da Força Eterna", type: ItemType.RING, rarity: Rarity.LEGENDARY, prompt: `${BASE_PROMPT} A thick band of adamantine with a glowing blue crystal, pulsing with the power of the earth.` },
      { id: "w-l-gloves", name: "Manoplas do Titã", type: ItemType.GLOVES, rarity: Rarity.LEGENDARY, prompt: `${BASE_PROMPT} ${GLOVES_POSE} Massive stone and metal gauntlets, glowing blue runes, capable of crushing mountains.` },
      { id: "w-l-pants", name: "Grevas do Colosso", type: ItemType.PANTS, rarity: Rarity.LEGENDARY, prompt: `${BASE_PROMPT} ${PANTS_POSE} Massive stone and metal leg armor, glowing runes of strength, earthquake cracks on surface.` },
    ],
  },
  Mage: {
    Common: [
      { id: "m-c-tiara", name: "Tiara de Aprendiz", type: ItemType.HELMET, rarity: Rarity.COMMON, prompt: `${BASE_PROMPT} A simple copper tiara, thin band, no gems.` },
      { id: "m-c-robe", name: "Manto de Tecido", type: ItemType.ARMOR, rarity: Rarity.COMMON, prompt: `${BASE_PROMPT} A simple grey cloth robe, hood attached, basic stitching.` },
      { id: "m-c-pants", name: "Calças de Tecido Leve", type: ItemType.PANTS, rarity: Rarity.COMMON, prompt: `${BASE_PROMPT} ${PANTS_POSE} Loose-fitting dark blue fabric trousers, comfortable for meditation.` },
      { id: "m-c-gloves", name: "Luvas de Tecido", type: ItemType.GLOVES, rarity: Rarity.COMMON, prompt: `${BASE_PROMPT} ${GLOVES_POSE} Simple dark blue cloth gloves, lightweight.` },
      { id: "m-c-boots", name: "Botas de Tecido", type: ItemType.BOOTS, rarity: Rarity.COMMON, prompt: `${BASE_PROMPT} ${BOOTS_POSE} Simple dark blue cloth boots with soft leather soles.` },
      { id: "m-c-ring", name: "Anel de Cobre", type: ItemType.RING, rarity: Rarity.COMMON, prompt: `${BASE_PROMPT} A simple copper ring, slightly oxidized.` },
      { id: "m-c-amulet", name: "Amuleto de Vidro", type: ItemType.AMULET, rarity: Rarity.COMMON, prompt: `${BASE_PROMPT} ${AMULET_POSE} A small glass orb on a simple string.` },
      { id: "m-c-staff", name: "Cajado de Aprendiz", type: ItemType.WEAPON, rarity: Rarity.COMMON, prompt: `${BASE_PROMPT} A simple wooden staff, smooth finish, small crystal at the tip.` },
      { id: "m-c-book", name: "Livro de Feitiços Básico", type: ItemType.OFFHAND, rarity: Rarity.COMMON, prompt: `${BASE_PROMPT} A small leather-bound book, plain cover, worn pages.` },
    ],
    Intermediate: [
      { id: "m-i-tiara", name: "Tiara de Prata", type: ItemType.HELMET, rarity: Rarity.INTERMEDIATE, prompt: `${BASE_PROMPT} A silver tiara with a small blue gem at the center, elegant design.` },
      { id: "m-i-robe", name: "Manto do Aprendiz", type: ItemType.ARMOR, rarity: Rarity.INTERMEDIATE, prompt: `${BASE_PROMPT} A blue silk robe with silver embroidery along the hem.` },
      { id: "m-i-pants", name: "Calças Rúnicas", type: ItemType.PANTS, rarity: Rarity.INTERMEDIATE, prompt: `${BASE_PROMPT} ${PANTS_POSE} Dark purple fabric trousers with faint silver runes embroidered along the sides.` },
      { id: "m-i-gloves", name: "Luvas de Seda", type: ItemType.GLOVES, rarity: Rarity.INTERMEDIATE, prompt: `${BASE_PROMPT} ${GLOVES_POSE} Fine purple silk gloves with silver thread embroidery.` },
      { id: "m-i-boots", name: "Botas de Seda", type: ItemType.BOOTS, rarity: Rarity.INTERMEDIATE, prompt: `${BASE_PROMPT} ${BOOTS_POSE} Purple silk boots with silver buckle clasps and reinforced soles.` },
      { id: "m-i-ring", name: "Anel de Prata", type: ItemType.RING, rarity: Rarity.INTERMEDIATE, prompt: `${BASE_PROMPT} A silver ring with a small glowing blue rune.` },
      { id: "m-i-amulet", name: "Amuleto de Cristal", type: ItemType.AMULET, rarity: Rarity.INTERMEDIATE, prompt: `${BASE_PROMPT} ${AMULET_POSE} A small glowing crystal shard on a silver chain.` },
      { id: "m-i-staff", name: "Cajado de Carvalho", type: ItemType.WEAPON, rarity: Rarity.INTERMEDIATE, prompt: `${BASE_PROMPT} A sturdy oak staff, silver bands, glowing blue gem at the top.` },
      { id: "m-i-book", name: "Grimório de Vidro", type: ItemType.OFFHAND, rarity: Rarity.INTERMEDIATE, prompt: `${BASE_PROMPT} A book with a glass-like cover, glowing runes visible inside.` },
    ],
    Excellent: [
      { id: "m-ex-tiara", name: "Coroa Arcaica", type: ItemType.HELMET, rarity: Rarity.EXCELLENT, prompt: `${BASE_PROMPT} An ornate silver crown with multiple purple gems, pulsing with energy.` },
      { id: "m-ex-robe", name: "Manto do Mestre", type: ItemType.ARMOR, rarity: Rarity.EXCELLENT, prompt: `${BASE_PROMPT} A deep purple velvet robe, gold trim, glowing sigils on shoulders.` },
      { id: "m-ex-pants", name: "Calças do Tece-Magia", type: ItemType.PANTS, rarity: Rarity.EXCELLENT, prompt: `${BASE_PROMPT} ${PANTS_POSE} Silk trousers that seem to shimmer with magical energy, layered fabric with gold thread.` },
      { id: "m-ex-gloves", name: "Luvas do Tece-Magia", type: ItemType.GLOVES, rarity: Rarity.EXCELLENT, prompt: `${BASE_PROMPT} ${GLOVES_POSE} Shimmering silk gloves with gold rune embroidery, pulsing with light.` },
      { id: "m-ex-boots", name: "Botas do Tece-Magia", type: ItemType.BOOTS, rarity: Rarity.EXCELLENT, prompt: `${BASE_PROMPT} ${BOOTS_POSE} Shimmering silk boots with gold buckle clasps, leaving faint magical trails.` },
      { id: "m-ex-ring", name: "Anel de Ouro Arcano", type: ItemType.RING, rarity: Rarity.EXCELLENT, prompt: `${BASE_PROMPT} A gold ring with a large pulsing purple amethyst.` },
      { id: "m-ex-amulet", name: "Amuleto Arcano", type: ItemType.AMULET, rarity: Rarity.EXCELLENT, prompt: `${BASE_PROMPT} ${AMULET_POSE} A large purple gemstone in an ornate gold setting on a gold chain.` },
      { id: "m-ex-staff", name: "Cajado de Cristal", type: ItemType.WEAPON, rarity: Rarity.EXCELLENT, prompt: `${BASE_PROMPT} A staff made of pure translucent crystal, pulsing with inner light, silver hilt.` },
      { id: "m-ex-book", name: "Códice Arcano", type: ItemType.OFFHAND, rarity: Rarity.EXCELLENT, prompt: `${BASE_PROMPT} A heavy tome bound in dragon leather, silver chains, floating magical sparks.` },
    ],
    Epic: [
      { id: "arcane-tiara", name: "Tiara do Sábio Arcano", type: ItemType.HELMET, rarity: Rarity.EPIC, prompt: `${BASE_PROMPT} Mage's tiara headpiece, dark silver curved band with a large purple amethyst crystal at center, silver runes engraved across the band, smaller crystals on each side, magical purple glow radiating from gems, ethereal wisps floating around it, color palette: dark silver, deep purple #6a0dad, arcane blue.` },
      { id: "arcane-robe", name: "Manto do Sábio Arcano", type: ItemType.ARMOR, rarity: Rarity.EPIC, prompt: `${BASE_PROMPT} Mage chest robe armor piece, dark midnight purple fabric with silver arcane rune embroidery along collar and chest, padded shoulders with silver pauldrons, glowing purple sigil at chest center, flowing fabric with dark lining, color palette: midnight purple #1a0a2e, silver #c0c0c0, glowing purple runes.` },
      { id: "arcane-boots", name: "Botas do Sábio Arcano", type: ItemType.BOOTS, rarity: Rarity.EPIC, prompt: `${BASE_PROMPT} ${BOOTS_POSE} Mage's pointed boots, dark purple leather with silver rune stitching along the shaft, slightly curled toe, silver buckle clasps, subtle purple glow at the sole as if hovering slightly, color palette: dark purple #1a0a2e, silver #c0c0c0.` },
      { id: "arcane-staff", name: "Cajado do Sábio Arcano", type: ItemType.WEAPON, rarity: Rarity.EPIC, prompt: `${BASE_PROMPT} Tall wizard staff, dark twisted wood shaft with silver bands, large purple amethyst crystal orb at the top held by silver claws, arcane runes glowing purple along the shaft, magical energy swirling around the crystal, color palette: dark wood, silver #c0c0c0, glowing purple #8a2be2.` },
      { id: "arcane-grimoire", name: "Grimório do Sábio Arcano", type: ItemType.OFFHAND, rarity: Rarity.EPIC, prompt: `${BASE_PROMPT} Ancient spellbook grimoire, dark leather cover with a large purple glowing eye embossed at center, silver metal corner reinforcements, arcane runes etched on cover, pages glowing faintly at edges, floating magical sparks around it, color palette: dark leather brown, silver #c0c0c0, purple glow #8a2be2.` },
      { id: "arcane-amulet", name: "Amuleto do Sábio Arcano", type: ItemType.AMULET, rarity: Rarity.EPIC, prompt: `${BASE_PROMPT} ${AMULET_POSE} Arcane mage amulet, a large teardrop purple amethyst crystal in a silver claw setting, hanging from a thin silver chain, runes etched on the metal setting, pulsing purple magical glow from within the gem, small arcane sparks floating around it, color palette: silver #c0c0c0, deep purple #6a0dad.` },
      { id: "arcane-ring", name: "Anel do Sábio Arcano", type: ItemType.RING, rarity: Rarity.EPIC, prompt: `${BASE_PROMPT} Thin elegant silver ring, tall setting holding a deep purple amethyst gemstone, arcane rune engraved on each side of the band, magical purple glow emanating from gem, refined and scholarly design, color palette: silver #c0c0c0, deep purple #6a0dad.` },
      { id: "arcane-gloves", name: "Luvas do Sábio Arcano", type: ItemType.GLOVES, rarity: Rarity.EPIC, prompt: `${BASE_PROMPT} ${GLOVES_POSE} Mage's fingerless gloves, dark purple leather with silver arcane runes embroidered on the back of the hand, silver ring reinforcements at knuckles, subtle purple glow at fingertips, color palette: dark purple #1a0a2e, silver #c0c0c0, purple glow.` },
      { id: "arcane-pants", name: "Calças do Sábio Arcano", type: ItemType.PANTS, rarity: Rarity.EPIC, prompt: `${BASE_PROMPT} ${PANTS_POSE} Mage's trousers, dark purple fabric with silver arcane rune embroidery along the sides, silver buckle clasps, subtle purple glow from the runes, color palette: dark purple #1a0a2e, silver #c0c0c0, purple glow.` },
    ],
    Legendary: [
      { id: "m-l-crown", name: "Coroa do Infinito", type: ItemType.HELMET, rarity: Rarity.LEGENDARY, prompt: `${BASE_PROMPT} A crown made of pure starlight and cosmic dust, a small galaxy spinning above it, ethereal glow.` },
      { id: "m-l-robe", name: "Manto do Infinito", type: ItemType.ARMOR, rarity: Rarity.LEGENDARY, prompt: `${BASE_PROMPT} A robe that looks like the night sky, moving stars and nebulae, translucent fabric.` },
      { id: "m-l-boots", name: "Passos Estelares", type: ItemType.BOOTS, rarity: Rarity.LEGENDARY, prompt: `${BASE_PROMPT} ${BOOTS_POSE} Boots made of woven moonlight, leaving trails of stardust, glowing silver fabric.` },
      { id: "m-l-staff", name: "Cajado da Eternidade", type: ItemType.WEAPON, rarity: Rarity.LEGENDARY, prompt: `${BASE_PROMPT} A staff made of starlight and cosmic dust, a small galaxy spinning at the top, ethereal glow.` },
      { id: "m-l-book", name: "Livro do Destino", type: ItemType.OFFHAND, rarity: Rarity.LEGENDARY, prompt: `${BASE_PROMPT} A book that floats in mid-air, pages made of light, constantly changing text, divine aura.` },
      { id: "m-l-amulet", name: "Olho do Cosmos", type: ItemType.AMULET, rarity: Rarity.LEGENDARY, prompt: `${BASE_PROMPT} ${AMULET_POSE} A pendant containing a swirling nebula, glowing with all the colors of the universe.` },
      { id: "m-l-ring", name: "Anel do Tempo", type: ItemType.RING, rarity: Rarity.LEGENDARY, prompt: `${BASE_PROMPT} A ring made of a single loop of light, small clockwork gears visible inside, glowing with gold energy.` },
      { id: "m-l-gloves", name: "Toque do Vazio", type: ItemType.GLOVES, rarity: Rarity.LEGENDARY, prompt: `${BASE_PROMPT} ${GLOVES_POSE} Translucent gloves made of dark energy and starlight, fingers seem to fade into nothingness.` },
      { id: "m-l-pants", name: "Calças do Infinito", type: ItemType.PANTS, rarity: Rarity.LEGENDARY, prompt: `${BASE_PROMPT} ${PANTS_POSE} Trousers made of woven moonlight, leaving trails of stardust, glowing silver fabric.` },
    ],
  },
  Hunter: {
    Common: [
      { id: "h-c-hood", name: "Capuz de Caçador", type: ItemType.HELMET, rarity: Rarity.COMMON, prompt: `${BASE_PROMPT} A simple green cloth hood, worn edges.` },
      { id: "h-c-armor", name: "Colete de Couro", type: ItemType.ARMOR, rarity: Rarity.COMMON, prompt: `${BASE_PROMPT} A light leather vest, dark brown, basic buckles.` },
      { id: "h-c-pants", name: "Calças de Caçador", type: ItemType.PANTS, rarity: Rarity.COMMON, prompt: `${BASE_PROMPT} ${PANTS_POSE} Rugged green fabric trousers, reinforced knees, simple design.` },
      { id: "h-c-gloves", name: "Luvas de Caçador", type: ItemType.GLOVES, rarity: Rarity.COMMON, prompt: `${BASE_PROMPT} ${GLOVES_POSE} Simple green cloth gloves, reinforced palms.` },
      { id: "h-c-boots", name: "Botas de Caçador", type: ItemType.BOOTS, rarity: Rarity.COMMON, prompt: `${BASE_PROMPT} ${BOOTS_POSE} Simple green cloth boots with leather soles, silent tread.` },
      { id: "h-c-ring", name: "Anel de Madeira", type: ItemType.RING, rarity: Rarity.COMMON, prompt: `${BASE_PROMPT} A simple wooden ring, carved from oak.` },
      { id: "h-c-amulet", name: "Amuleto de Garra", type: ItemType.AMULET, rarity: Rarity.COMMON, prompt: `${BASE_PROMPT} ${AMULET_POSE} A small animal claw on a leather cord.` },
      { id: "h-c-bow", name: "Arco Curto de Madeira", type: ItemType.WEAPON, rarity: Rarity.COMMON, prompt: `${BASE_PROMPT} A simple wooden shortbow, plain string, basic grip.` },
      { id: "h-c-dagger", name: "Adaga de Ferro", type: ItemType.OFFHAND, rarity: Rarity.COMMON, prompt: `${BASE_PROMPT} A small iron dagger, wooden handle, simple sheath.` },
      { id: "h-c-quiver", name: "Cesto de Flechas Simples", type: ItemType.QUIVER, rarity: Rarity.COMMON, prompt: `${BASE_PROMPT} ${QUIVER_POSE} A plain brown leather quiver, basic arrows with white feathers.` },
    ],
    Intermediate: [
      { id: "h-i-hood", name: "Capuz de Couro", type: ItemType.HELMET, rarity: Rarity.INTERMEDIATE, prompt: `${BASE_PROMPT} A dark green leather hood with a small silver clasp.` },
      { id: "h-i-armor", name: "Armadura de Couro Reforçada", type: ItemType.ARMOR, rarity: Rarity.INTERMEDIATE, prompt: `${BASE_PROMPT} Layered leather chest armor, metal studs, dark green finish.` },
      { id: "h-i-pants", name: "Calças de Couro Flexível", type: ItemType.PANTS, rarity: Rarity.INTERMEDIATE, prompt: `${BASE_PROMPT} ${PANTS_POSE} Dark green flexible leather trousers, silent movement design.` },
      { id: "h-i-gloves", name: "Luvas de Couro Flexível", type: ItemType.GLOVES, rarity: Rarity.INTERMEDIATE, prompt: `${BASE_PROMPT} ${GLOVES_POSE} Dark green flexible leather gloves, reinforced knuckles.` },
      { id: "h-i-boots", name: "Botas de Couro Flexível", type: ItemType.BOOTS, rarity: Rarity.INTERMEDIATE, prompt: `${BASE_PROMPT} ${BOOTS_POSE} Dark green leather boots, silent soles, silver buckles.` },
      { id: "h-i-ring", name: "Anel de Prata", type: ItemType.RING, rarity: Rarity.INTERMEDIATE, prompt: `${BASE_PROMPT} A silver ring with a small engraved leaf pattern.` },
      { id: "h-i-amulet", name: "Amuleto de Presa", type: ItemType.AMULET, rarity: Rarity.INTERMEDIATE, prompt: `${BASE_PROMPT} ${AMULET_POSE} A large predator's fang on a silver chain.` },
      { id: "h-i-bow", name: "Arco de Teixo", type: ItemType.WEAPON, rarity: Rarity.INTERMEDIATE, prompt: `${BASE_PROMPT} A sturdy yew longbow, leather grip, carved patterns.` },
      { id: "h-i-dagger", name: "Adaga de Aço", type: ItemType.OFFHAND, rarity: Rarity.INTERMEDIATE, prompt: `${BASE_PROMPT} A sharp steel dagger, bone handle, engraved guard.` },
      { id: "h-i-quiver", name: "Cesto de Flechas de Couro", type: ItemType.QUIVER, rarity: Rarity.INTERMEDIATE, prompt: `${BASE_PROMPT} ${QUIVER_POSE} A reinforced leather quiver, arrows with green feathers, simple carvings.` },
    ],
    Excellent: [
      { id: "h-ex-hood", name: "Capuz de Escamas", type: ItemType.HELMET, rarity: Rarity.EXCELLENT, prompt: `${BASE_PROMPT} A hood made of green dragon scales, glowing emerald eyes on the sides.` },
      { id: "h-ex-armor", name: "Armadura de Escamas", type: ItemType.ARMOR, rarity: Rarity.EXCELLENT, prompt: `${BASE_PROMPT} Chest armor made of small green dragon scales, lightweight and strong.` },
      { id: "h-ex-pants", name: "Calças de Escamas", type: ItemType.PANTS, rarity: Rarity.EXCELLENT, prompt: `${BASE_PROMPT} ${PANTS_POSE} Trousers with green scale reinforcements on thighs and shins, dark leather base.` },
      { id: "h-ex-gloves", name: "Luvas de Escamas", type: ItemType.GLOVES, rarity: Rarity.EXCELLENT, prompt: `${BASE_PROMPT} ${GLOVES_POSE} Green scale gauntlets, lightweight and flexible, emerald trim.` },
      { id: "h-ex-boots", name: "Botas de Escamas", type: ItemType.BOOTS, rarity: Rarity.EXCELLENT, prompt: `${BASE_PROMPT} ${BOOTS_POSE} Green scale boots, silent and durable, emerald buckle clasps.` },
      { id: "h-ex-ring", name: "Anel de Esmeralda", type: ItemType.RING, rarity: Rarity.EXCELLENT, prompt: `${BASE_PROMPT} A silver ring with a large glowing emerald.` },
      { id: "h-ex-amulet", name: "Amuleto de Esmeralda", type: ItemType.AMULET, rarity: Rarity.EXCELLENT, prompt: `${BASE_PROMPT} ${AMULET_POSE} A glowing emerald shard in a silver leaf setting on a silver chain.` },
      { id: "h-ex-bow", name: "Arco Composto", type: ItemType.WEAPON, rarity: Rarity.EXCELLENT, prompt: `${BASE_PROMPT} A high-tension composite bow, bone and wood, silver string, glowing runes.` },
      { id: "h-ex-dagger", name: "Adaga Élfica", type: ItemType.OFFHAND, rarity: Rarity.EXCELLENT, prompt: `${BASE_PROMPT} A slender silver dagger, leaf-shaped blade, emerald in hilt.` },
      { id: "h-ex-quiver", name: "Cesto de Flechas Élfico", type: ItemType.QUIVER, rarity: Rarity.EXCELLENT, prompt: `${BASE_PROMPT} ${QUIVER_POSE} An ornate silver and wood quiver, leaf patterns, arrows with emerald tips.` },
    ],
    Epic: [
      { id: "shadow-hood", name: "Capuz do Caçador das Sombras", type: ItemType.HELMET, rarity: Rarity.EPIC, prompt: `${BASE_PROMPT} Ranger hood and mask, dark forest green leather hood with black fabric, lower face mask with emerald green eye slit, small leaves and feather ornaments on side, dark stitching detail, subtle shadow texture, color palette: dark green #1a3a1a, black #06090f, emerald #50c878.` },
      { id: "shadow-vest", name: "Colete do Caçador das Sombras", type: ItemType.ARMOR, rarity: Rarity.EPIC, prompt: `${BASE_PROMPT} Ranger leather chest armor, layered dark green and black leather plates, padded shoulders with small emerald green gems, quiver strap across chest, dark metal buckles, reinforced stitching visible, scratched and worn from use, color palette: dark green #1a3a1a, black #06090f, emerald highlights #50c878.` },
      { id: "shadow-boots", name: "Botas do Caçador das Sombras", type: ItemType.BOOTS, rarity: Rarity.EPIC, prompt: `${BASE_PROMPT} ${BOOTS_POSE} Ranger leather boots, tall dark green leather with black reinforced toe and heel, thin laces up the front, soft sole for silent movement, small emerald gem clasp at ankle, color palette: dark green #1a3a1a, black #06090f, emerald #50c878.` },
      { id: "shadow-bow", name: "Arco do Caçador das Sombras", type: ItemType.WEAPON, rarity: Rarity.EPIC, prompt: `${BASE_PROMPT} Recurve longbow, dark black wood with emerald green sinew string, carved runes along the limbs with green glow, silver tip reinforcements at each end, an arrow nocked and ready, subtle wind energy wisps around the string, color palette: black wood, emerald #50c878, silver tips.` },
      { id: "shadow-dagger", name: "Adaga do Caçador das Sombras", type: ItemType.OFFHAND, rarity: Rarity.EPIC, prompt: `${BASE_PROMPT} Assassin's short dagger, black blade with a serrated back edge, emerald green venom channel along the blade, wrapped dark leather grip with green cord binding, crossguard shaped like a curved fang, green poison drip effect on blade tip, color palette: black #06090f, emerald #50c878, dark leather.` },
      { id: "shadow-amulet", name: "Amuleto do Caçador das Sombras", type: ItemType.AMULET, rarity: Rarity.EPIC, prompt: `${BASE_PROMPT} ${AMULET_POSE} Hunter's amulet, carved dark bone or antler pendant in the shape of a crescent moon, small emerald gem at center, thin dark leather cord, nature-worn texture with small rune carvings, faint green energy glow at the gem, color palette: bone white/dark, emerald #50c878, dark cord.` },
      { id: "shadow-ring", name: "Anel do Caçador das Sombras", type: ItemType.RING, rarity: Rarity.EPIC, prompt: `${BASE_PROMPT} Dark rough-cut iron ring, wide band with a flat emerald gemstone set flush into the metal, small carved leaves on each side of the setting, worn and scratched from use, faint green magical shimmer on the stone, color palette: dark iron #2a2a2a, emerald #50c878.` },
      { id: "shadow-gloves", name: "Luvas do Caçador das Sombras", type: ItemType.GLOVES, rarity: Rarity.EPIC, prompt: `${BASE_PROMPT} ${GLOVES_POSE} Ranger leather gloves, dark green leather with black reinforced knuckle pads, cut fingertips for better grip, thin emerald green stitching detail on back of hand, worn and flexible texture, color palette: dark green #1a3a1a, black #06090f, emerald #50c878.` },
      { id: "shadow-pants", name: "Calças do Caçador das Sombras", type: ItemType.PANTS, rarity: Rarity.EPIC, prompt: `${BASE_PROMPT} ${PANTS_POSE} Ranger leather trousers, dark green leather with black reinforced knee pads, thin emerald green stitching detail, worn and flexible texture, color palette: dark green #1a3a1a, black #06090f, emerald #50c878.` },
      { id: "shadow-quiver", name: "Cesto de Flechas das Sombras", type: ItemType.QUIVER, rarity: Rarity.EPIC, prompt: `${BASE_PROMPT} ${QUIVER_POSE} A dark green leather quiver with black metal trim, emerald green runes glowing on the side, arrows with black shafts and green feathers.` },
    ],
    Legendary: [
      { id: "h-l-helm", name: "Máscara do Espírito da Floresta", type: ItemType.HELMET, rarity: Rarity.LEGENDARY, prompt: `${BASE_PROMPT} A mask made of living wood and glowing leaves, moving vines, divine nature energy.` },
      { id: "h-l-armor", name: "Manto da Floresta Viva", type: ItemType.ARMOR, rarity: Rarity.LEGENDARY, prompt: `${BASE_PROMPT} Chest armor made of living wood and glowing leaves, moving vines, divine nature energy.` },
      { id: "h-l-boots", name: "Passos da Sombra", type: ItemType.BOOTS, rarity: Rarity.LEGENDARY, prompt: `${BASE_PROMPT} ${BOOTS_POSE} Boots that seem to blend into the shadows, dark smoke-like fabric, glowing green runes.` },
      { id: "h-l-bow", name: "Sopro do Vento", type: ItemType.WEAPON, rarity: Rarity.LEGENDARY, prompt: `${BASE_PROMPT} A bow made of pure wind and light, translucent limbs, arrows that materialize from air, ethereal green glow.` },
      { id: "h-l-dagger", name: "Presa de Fenrir", type: ItemType.OFFHAND, rarity: Rarity.LEGENDARY, prompt: `${BASE_PROMPT} A dagger made of a giant wolf's tooth, dripping with frost and shadow, bone handle.` },
      { id: "h-l-amulet", name: "Coração da Natureza", type: ItemType.AMULET, rarity: Rarity.LEGENDARY, prompt: `${BASE_PROMPT} ${AMULET_POSE} A pendant made of a glowing emerald seed, surrounded by moving silver vines.` },
      { id: "h-l-ring", name: "Anel do Predador", type: ItemType.RING, rarity: Rarity.LEGENDARY, prompt: `${BASE_PROMPT} A ring made of a single silver claw, glowing with green primal energy.` },
      { id: "h-l-gloves", name: "Garras da Floresta", type: ItemType.GLOVES, rarity: Rarity.LEGENDARY, prompt: `${BASE_PROMPT} ${GLOVES_POSE} Gloves made of living wood and sharp thorns, glowing with nature's wrath.` },
      { id: "h-l-pants", name: "Calças da Floresta Viva", type: ItemType.PANTS, rarity: Rarity.LEGENDARY, prompt: `${BASE_PROMPT} ${PANTS_POSE} Trousers that seem to blend into the shadows, dark smoke-like fabric, glowing green runes of speed.` },
      { id: "h-l-quiver", name: "Cesto do Infinito", type: ItemType.QUIVER, rarity: Rarity.LEGENDARY, prompt: `${BASE_PROMPT} ${QUIVER_POSE} A quiver made of celestial wood, glowing with golden light, arrows that never run out.` },
    ],
  },
  Lord: {
    Common: [
      { id: "l-c-crown", name: "Coroa de Bronze", type: ItemType.HELMET, rarity: Rarity.COMMON, prompt: `${BASE_PROMPT} A simple bronze crown, plain design, no gems.` },
      { id: "l-c-armor", name: "Gibão de Veludo", type: ItemType.ARMOR, rarity: Rarity.COMMON, prompt: `${BASE_PROMPT} A red velvet doublet with leather reinforcements, gold buttons.` },
      { id: "l-c-pants", name: "Calças Reais", type: ItemType.PANTS, rarity: Rarity.COMMON, prompt: `${BASE_PROMPT} ${PANTS_POSE} Fine red fabric trousers with gold embroidery along the seams, royal style.` },
      { id: "l-c-gloves", name: "Luvas de Veludo", type: ItemType.GLOVES, rarity: Rarity.COMMON, prompt: `${BASE_PROMPT} ${GLOVES_POSE} Red velvet gloves with gold thread embroidery.` },
      { id: "l-c-boots", name: "Botas de Veludo", type: ItemType.BOOTS, rarity: Rarity.COMMON, prompt: `${BASE_PROMPT} ${BOOTS_POSE} Red velvet boots with gold buckle clasps and soft soles.` },
      { id: "l-c-ring", name: "Anel de Bronze Nobre", type: ItemType.RING, rarity: Rarity.COMMON, prompt: `${BASE_PROMPT} A bronze signet ring with a simple shield engraving.` },
      { id: "l-c-amulet", name: "Amuleto de Bronze", type: ItemType.AMULET, rarity: Rarity.COMMON, prompt: `${BASE_PROMPT} ${AMULET_POSE} A bronze medallion on a simple chain.` },
      { id: "l-c-sword", name: "Espada Cerimonial", type: ItemType.WEAPON, rarity: Rarity.COMMON, prompt: `${BASE_PROMPT} A polished steel sword, gold-plated crossguard, red velvet grip, more for show than battle.` },
      { id: "l-c-shield", name: "Escudo Heráldico", type: ItemType.OFFHAND, rarity: Rarity.COMMON, prompt: `${BASE_PROMPT} A wooden shield with a simple coat of arms painted on it, iron rim.` },
    ],
    Intermediate: [
      { id: "l-i-crown", name: "Coroa de Prata", type: ItemType.HELMET, rarity: Rarity.INTERMEDIATE, prompt: `${BASE_PROMPT} A silver crown with a small ruby at the center, elegant design.` },
      { id: "l-i-armor", name: "Armadura de Gala", type: ItemType.ARMOR, rarity: Rarity.INTERMEDIATE, prompt: `${BASE_PROMPT} Polished steel chest armor with gold filigree, red sash across chest.` },
      { id: "l-i-pants", name: "Calças de Cavalaria", type: ItemType.PANTS, rarity: Rarity.INTERMEDIATE, prompt: `${BASE_PROMPT} ${PANTS_POSE} Dark red leather trousers with gold buckle clasps and silver thread patterns.` },
      { id: "l-i-gloves", name: "Manoplas de Gala", type: ItemType.GLOVES, rarity: Rarity.INTERMEDIATE, prompt: `${BASE_PROMPT} ${GLOVES_POSE} Polished steel gauntlets with gold filigree and red velvet lining.` },
      { id: "l-i-boots", name: "Botas de Cavalaria", type: ItemType.BOOTS, rarity: Rarity.INTERMEDIATE, prompt: `${BASE_PROMPT} ${BOOTS_POSE} Polished steel sabatons with gold trim and red velvet accents.` },
      { id: "l-i-ring", name: "Anel de Prata Nobre", type: ItemType.RING, rarity: Rarity.INTERMEDIATE, prompt: `${BASE_PROMPT} A silver signet ring with an engraved lion crest.` },
      { id: "l-i-amulet", name: "Amuleto de Prata Nobre", type: ItemType.AMULET, rarity: Rarity.INTERMEDIATE, prompt: `${BASE_PROMPT} ${AMULET_POSE} A silver medallion with a small ruby on a silver chain.` },
      { id: "l-i-sword", name: "Espada do Nobre", type: ItemType.WEAPON, rarity: Rarity.INTERMEDIATE, prompt: `${BASE_PROMPT} A high-quality steel sword, silver hilt, small ruby in pommel, elegant design.` },
      { id: "l-i-shield", name: "Escudo do Brasão", type: ItemType.OFFHAND, rarity: Rarity.INTERMEDIATE, prompt: `${BASE_PROMPT} A steel heater shield with an embossed lion emblem, silver trim.` },
    ],
    Excellent: [
      { id: "l-ex-crown", name: "Coroa de Ouro", type: ItemType.HELMET, rarity: Rarity.EXCELLENT, prompt: `${BASE_PROMPT} A golden crown with multiple rubies and sapphires, majestic design.` },
      { id: "l-ex-armor", name: "Armadura do Comandante", type: ItemType.ARMOR, rarity: Rarity.EXCELLENT, prompt: `${BASE_PROMPT} Heavy plate armor with intricate gold engravings, lion-head pauldrons.` },
      { id: "l-ex-pants", name: "Grevas do Monarca", type: ItemType.PANTS, rarity: Rarity.EXCELLENT, prompt: `${BASE_PROMPT} ${PANTS_POSE} Gold-plated leg armor with crimson velvet lining, lion emblems on knees.` },
      { id: "l-ex-gloves", name: "Manoplas do Monarca", type: ItemType.GLOVES, rarity: Rarity.EXCELLENT, prompt: `${BASE_PROMPT} ${GLOVES_POSE} Gold-plated gauntlets with intricate engravings and crimson velvet lining.` },
      { id: "l-ex-boots", name: "Botas do Monarca", type: ItemType.BOOTS, rarity: Rarity.EXCELLENT, prompt: `${BASE_PROMPT} ${BOOTS_POSE} Gold-plated sabatons with lion head emblems and crimson velvet accents.` },
      { id: "l-ex-ring", name: "Anel de Ouro Real", type: ItemType.RING, rarity: Rarity.EXCELLENT, prompt: `${BASE_PROMPT} A gold signet ring with a large sapphire and engraved crown.` },
      { id: "l-ex-amulet", name: "Amuleto de Ouro Real", type: ItemType.AMULET, rarity: Rarity.EXCELLENT, prompt: `${BASE_PROMPT} ${AMULET_POSE} A large sapphire in an ornate gold crown setting on a gold chain.` },
      { id: "l-ex-sword", name: "Lâmina da Justiça", type: ItemType.WEAPON, rarity: Rarity.EXCELLENT, prompt: `${BASE_PROMPT} A golden-hued steel sword, blue sapphire in hilt, glowing white aura.` },
      { id: "l-ex-shield", name: "Escudo do Reino", type: ItemType.OFFHAND, rarity: Rarity.EXCELLENT, prompt: `${BASE_PROMPT} A large shield made of white steel and gold, crown emblem at center.` },
    ],
    Epic: [
      { id: "l-ep-helm", name: "Coroa do Lorde Vassalo", type: ItemType.HELMET, rarity: Rarity.EPIC, prompt: `${BASE_PROMPT} A majestic golden crown-helmet, open face design with protective cheek guards, large central ruby, intricate engravings of laurel leaves, glowing with divine authority, color palette: gold #ffd700, crimson velvet.` },
      { id: "l-ep-armor", name: "Couraça do Lorde Vassalo", type: ItemType.ARMOR, rarity: Rarity.EPIC, prompt: `${BASE_PROMPT} Majestic full plate armor, pure gold with crimson velvet details, crown emblem on chest, glowing with divine light, color palette: gold #ffd700, crimson velvet.` },
      { id: "l-ep-boots", name: "Botas do Lorde Vassalo", type: ItemType.BOOTS, rarity: Rarity.EPIC, prompt: `${BASE_PROMPT} ${BOOTS_POSE} Royal golden sabatons, polished gold plates over crimson velvet, lion head emblems on the ankles, ornate engravings, color palette: gold #ffd700, crimson velvet.` },
      { id: "l-ep-sword", name: "Soberana", type: ItemType.WEAPON, rarity: Rarity.EPIC, prompt: `${BASE_PROMPT} A legendary sword with a blade of pure gold-steel, hilt shaped like a dragon's wings, large ruby at center, pulsing with leadership energy, color palette: gold #ffd700, steel.` },
      { id: "l-ep-shield", name: "Baluarte do Rei", type: ItemType.OFFHAND, rarity: Rarity.EPIC, prompt: `${BASE_PROMPT} A massive shield made of enchanted gold and white marble, glowing crown sigil, impenetrable aura, color palette: gold #ffd700, white marble.` },
      { id: "l-ep-amulet", name: "Amuleto da Coroa", type: ItemType.AMULET, rarity: Rarity.EPIC, prompt: `${BASE_PROMPT} ${AMULET_POSE} A golden crown-shaped pendant on a heavy gold chain, large central ruby, glowing with authority, color palette: gold #ffd700, crimson ruby.` },
      { id: "l-ep-ring", name: "Selo do Reino", type: ItemType.RING, rarity: Rarity.EPIC, prompt: `${BASE_PROMPT} A heavy gold signet ring, large flat top with an engraved lion crest, ruby accents on the sides, glowing with royal power, color palette: gold #ffd700, ruby.` },
      { id: "l-ep-gloves", name: "Manoplas do Lorde Vassalo", type: ItemType.GLOVES, rarity: Rarity.EPIC, prompt: `${BASE_PROMPT} ${GLOVES_POSE} Ornate golden gauntlets, polished gold plates with crimson velvet lining at the wrists, lion head engravings on the back of the hands, color palette: gold #ffd700, crimson velvet.` },
      { id: "l-ep-pants", name: "Calças do Lorde Vassalo", type: ItemType.PANTS, rarity: Rarity.EPIC, prompt: `${BASE_PROMPT} ${PANTS_POSE} Royal leg armor, gold plates over crimson velvet, intricate engravings of historical battles, glowing runes, color palette: gold #ffd700, crimson velvet.` },
    ],
    Legendary: [
      { id: "l-l-helm", name: "Coroa dos Deuses", type: ItemType.HELMET, rarity: Rarity.LEGENDARY, prompt: `${BASE_PROMPT} A crown made of pure celestial gold and white light, floating wings, divine aura.` },
      { id: "l-l-armor", name: "Armadura do Deus-Rei", type: ItemType.ARMOR, rarity: Rarity.LEGENDARY, prompt: `${BASE_PROMPT} Armor made of pure celestial gold and white light, floating wings, divine aura.` },
      { id: "l-l-boots", name: "Passos da Realeza", type: ItemType.BOOTS, rarity: Rarity.LEGENDARY, prompt: `${BASE_PROMPT} ${BOOTS_POSE} Boots made of woven gold and light, leaving trails of golden dust, glowing with power.` },
      { id: "l-l-sword", name: "Excalibur", type: ItemType.WEAPON, rarity: Rarity.LEGENDARY, prompt: `${BASE_PROMPT} The legendary sword of kings, blade of pure light, hilt of divine gold and gems, blinding radiance.` },
      { id: "l-l-shield", name: "Escudo do Olimpo", type: ItemType.OFFHAND, rarity: Rarity.LEGENDARY, prompt: `${BASE_PROMPT} A shield made of divine bronze and light, medusa head emblem that glows, lightning sparks.` },
      { id: "l-l-amulet", name: "Selo de Zeus", type: ItemType.AMULET, rarity: Rarity.LEGENDARY, prompt: `${BASE_PROMPT} ${AMULET_POSE} A pendant made of a single lightning bolt encased in crystal, glowing with divine electricity.` },
      { id: "l-l-ring", name: "Anel do Olimpo", type: ItemType.RING, rarity: Rarity.LEGENDARY, prompt: `${BASE_PROMPT} A ring made of white gold with a glowing lightning bolt emblem, pulsing with divine power.` },
      { id: "l-l-gloves", name: "Toque de Midas", type: ItemType.GLOVES, rarity: Rarity.LEGENDARY, prompt: `${BASE_PROMPT} ${GLOVES_POSE} Golden gauntlets that turn everything they touch into gold, glowing with divine greed.` },
      { id: "l-l-pants", name: "Grevas da Realeza", type: ItemType.PANTS, rarity: Rarity.LEGENDARY, prompt: `${BASE_PROMPT} ${PANTS_POSE} Leg armor made of woven gold and light, leaving trails of golden dust, glowing with power.` },
    ],
  },
  Assassin: {
    Common: [
      { id: "a-c-dagger", name: "Adaga de Ferro", type: ItemType.WEAPON, rarity: Rarity.COMMON, prompt: `${BASE_PROMPT} A simple iron dagger, dark handle, basic sheath.` },
      { id: "a-c-blade", name: "Lâmina Oculta", type: ItemType.OFFHAND, rarity: Rarity.COMMON, prompt: `${BASE_PROMPT} A small wrist-mounted blade, simple mechanism, leather strap.` },
      { id: "a-c-armor", name: "Traje de Couro", type: ItemType.ARMOR, rarity: Rarity.COMMON, prompt: `${BASE_PROMPT} A dark leather vest, tight-fitting, basic buckles.` },
      { id: "a-c-pants", name: "Calças de Furtividade", type: ItemType.PANTS, rarity: Rarity.COMMON, prompt: `${BASE_PROMPT} ${PANTS_POSE} Tight dark grey fabric trousers, silent movement design.` },
      { id: "a-c-helm", name: "Capuz de Pano", type: ItemType.HELMET, rarity: Rarity.COMMON, prompt: `${BASE_PROMPT} A simple dark grey cloth hood, covering the head and neck.` },
      { id: "a-c-gloves", name: "Luvas de Couro", type: ItemType.GLOVES, rarity: Rarity.COMMON, prompt: `${BASE_PROMPT} ${GLOVES_POSE} Simple dark leather gloves, tight fit, worn texture.` },
      { id: "a-c-boots", name: "Botas de Pano", type: ItemType.BOOTS, rarity: Rarity.COMMON, prompt: `${BASE_PROMPT} ${BOOTS_POSE} Simple dark cloth boots with soft leather soles for silent steps.` },
      { id: "a-c-ring", name: "Anel de Ferro", type: ItemType.RING, rarity: Rarity.COMMON, prompt: `${BASE_PROMPT} A plain iron ring, dark finish, no decorations.` },
      { id: "a-c-amulet", name: "Amuleto de Corda", type: ItemType.AMULET, rarity: Rarity.COMMON, prompt: `${BASE_PROMPT} ${AMULET_POSE} A simple dark cord with a small iron coin pendant.` },
    ],
    Intermediate: [
      { id: "a-i-dagger", name: "Adaga de Aço", type: ItemType.WEAPON, rarity: Rarity.INTERMEDIATE, prompt: `${BASE_PROMPT} A sharp steel dagger, serrated edge, leather-wrapped handle.` },
      { id: "a-i-blade", name: "Lâmina de Pulso", type: ItemType.OFFHAND, rarity: Rarity.INTERMEDIATE, prompt: `${BASE_PROMPT} A steel wrist blade, spring-loaded, engraved guard.` },
      { id: "a-i-armor", name: "Armadura de Couro Batido", type: ItemType.ARMOR, rarity: Rarity.INTERMEDIATE, prompt: `${BASE_PROMPT} Hardened black leather chest armor, metal studs, dark finish.` },
      { id: "a-i-pants", name: "Calças de Couro Negro", type: ItemType.PANTS, rarity: Rarity.INTERMEDIATE, prompt: `${BASE_PROMPT} ${PANTS_POSE} Black flexible leather trousers with reinforced knees and dark stitching.` },
      { id: "a-i-helm", name: "Máscara de Couro", type: ItemType.HELMET, rarity: Rarity.INTERMEDIATE, prompt: `${BASE_PROMPT} A hardened black leather mask covering the lower face, metal rivets.` },
      { id: "a-i-gloves", name: "Luvas de Couro Batido", type: ItemType.GLOVES, rarity: Rarity.INTERMEDIATE, prompt: `${BASE_PROMPT} ${GLOVES_POSE} Hardened black leather gloves with metal studs on knuckles.` },
      { id: "a-i-boots", name: "Botas de Couro Negro", type: ItemType.BOOTS, rarity: Rarity.INTERMEDIATE, prompt: `${BASE_PROMPT} ${BOOTS_POSE} Hardened black leather boots with reinforced toes and silent soles.` },
      { id: "a-i-ring", name: "Anel de Aço", type: ItemType.RING, rarity: Rarity.INTERMEDIATE, prompt: `${BASE_PROMPT} A polished steel ring with a small dark onyx stone.` },
      { id: "a-i-amulet", name: "Amuleto de Aço", type: ItemType.AMULET, rarity: Rarity.INTERMEDIATE, prompt: `${BASE_PROMPT} ${AMULET_POSE} A steel medallion with a raven engraving on a dark chain.` },
    ],
    Excellent: [
      { id: "a-ex-dagger", name: "Adaga de Veneno", type: ItemType.WEAPON, rarity: Rarity.EXCELLENT, prompt: `${BASE_PROMPT} A green-tinted steel dagger, dripping venom, bone handle.` },
      { id: "a-ex-blade", name: "Lâmina das Sombras", type: ItemType.OFFHAND, rarity: Rarity.EXCELLENT, prompt: `${BASE_PROMPT} A blade made of dark metal, glowing purple runes, smoke-like aura.` },
      { id: "a-ex-armor", name: "Traje do Assassino", type: ItemType.ARMOR, rarity: Rarity.EXCELLENT, prompt: `${BASE_PROMPT} Dark leather armor with crimson highlights, hidden pockets, throwing knives attached.` },
      { id: "a-ex-pants", name: "Calças do Carrasco", type: ItemType.PANTS, rarity: Rarity.EXCELLENT, prompt: `${BASE_PROMPT} ${PANTS_POSE} Dark leather trousers with crimson silk lining, hidden blade compartments.` },
      { id: "a-ex-helm", name: "Capuz do Carrasco", type: ItemType.HELMET, rarity: Rarity.EXCELLENT, prompt: `${BASE_PROMPT} A dark leather hood with crimson silk lining, partially covering the face.` },
      { id: "a-ex-gloves", name: "Luvas do Carrasco", type: ItemType.GLOVES, rarity: Rarity.EXCELLENT, prompt: `${BASE_PROMPT} ${GLOVES_POSE} Dark leather gloves with crimson silk lining and hidden blade slots.` },
      { id: "a-ex-boots", name: "Botas do Carrasco", type: ItemType.BOOTS, rarity: Rarity.EXCELLENT, prompt: `${BASE_PROMPT} ${BOOTS_POSE} Dark leather boots with crimson silk lining and silent soles.` },
      { id: "a-ex-ring", name: "Anel de Prata Negra", type: ItemType.RING, rarity: Rarity.EXCELLENT, prompt: `${BASE_PROMPT} A black silver ring with a glowing purple amethyst.` },
      { id: "a-ex-amulet", name: "Amuleto de Prata Negra", type: ItemType.AMULET, rarity: Rarity.EXCELLENT, prompt: `${BASE_PROMPT} ${AMULET_POSE} A black silver pendant with a skull engraving and a purple gem.` },
    ],
    Epic: [
      { id: "a-ep-mask", name: "Máscara do Vulto", type: ItemType.HELMET, rarity: Rarity.EPIC, prompt: `${BASE_PROMPT} A dark leather mask covering the entire face, glowing red eye slits, skull-like engravings, smoke-like aura, color palette: black #0a0a0a, crimson #ff0000.` },
      { id: "a-ep-armor", name: "Armadura do Mestre Assassino", type: ItemType.ARMOR, rarity: Rarity.EPIC, prompt: `${BASE_PROMPT} Full leather armor, black with crimson glow, skull pauldrons, glowing runes of death, color palette: black #0a0a0a, crimson #ff0000.` },
      { id: "a-ep-boots", name: "Botas do Vulto", type: ItemType.BOOTS, rarity: Rarity.EPIC, prompt: `${BASE_PROMPT} ${BOOTS_POSE} Silent dark leather boots, crimson stitching, reinforced toe with hidden blade, smoke-like aura around the soles, color palette: black #0a0a0a, crimson #ff0000.` },
      { id: "a-ep-dagger", name: "Sussurro da Morte", type: ItemType.WEAPON, rarity: Rarity.EPIC, prompt: `${BASE_PROMPT} A dagger with a blade of pure shadow, hilt shaped like a skull, glowing red eyes, silent aura, color palette: black #0a0a0a, crimson #ff0000.` },
      { id: "a-ep-blade", name: "Lâmina do Caos", type: ItemType.OFFHAND, rarity: Rarity.EPIC, prompt: `${BASE_PROMPT} A jagged blade made of obsidian, glowing red cracks, dripping blood-like energy, color palette: black #0a0a0a, crimson #ff0000.` },
      { id: "a-ep-amulet", name: "Amuleto do Corvo", type: ItemType.AMULET, rarity: Rarity.EPIC, prompt: `${BASE_PROMPT} ${AMULET_POSE} A silver crow-head pendant on a dark chain, glowing red eyes, shadow energy, color palette: silver, crimson #ff0000.` },
      { id: "a-ep-ring", name: "Anel da Viúva", type: ItemType.RING, rarity: Rarity.EPIC, prompt: `${BASE_PROMPT} A thin black metal ring with a small spider-shaped ruby, glowing with poison energy, color palette: black #0a0a0a, crimson #ff0000.` },
      { id: "a-ep-gloves", name: "Luvas do Vulto", type: ItemType.GLOVES, rarity: Rarity.EPIC, prompt: `${BASE_PROMPT} ${GLOVES_POSE} Dark leather gloves with crimson rune embroidery, hidden compartments for poison needles, articulated fingers, color palette: black #0a0a0a, crimson #ff0000.` },
      { id: "a-ep-pants", name: "Calças do Vulto", type: ItemType.PANTS, rarity: Rarity.EPIC, prompt: `${BASE_PROMPT} ${PANTS_POSE} Trousers that seem to flicker in and out of existence, dark smoke fabric, glowing red runes, color palette: black #0a0a0a, crimson #ff0000.` },
    ],
    Legendary: [
      { id: "a-l-mask", name: "Máscara da Noite Eterna", type: ItemType.HELMET, rarity: Rarity.LEGENDARY, prompt: `${BASE_PROMPT} A mask made of pure shadow and starlight, translucent, moving darkness.` },
      { id: "a-l-armor", name: "Manto da Noite Eterna", type: ItemType.ARMOR, rarity: Rarity.LEGENDARY, prompt: `${BASE_PROMPT} Armor made of pure shadow and starlight, translucent, moving darkness.` },
      { id: "a-l-boots", name: "Passos do Abismo", type: ItemType.BOOTS, rarity: Rarity.LEGENDARY, prompt: `${BASE_PROMPT} ${BOOTS_POSE} Boots made of pure void energy, leaving trails of darkness, glowing purple runes.` },
      { id: "a-l-dagger", name: "Lâmina do Vazio", type: ItemType.WEAPON, rarity: Rarity.LEGENDARY, prompt: `${BASE_PROMPT} A dagger that is a literal hole in reality, sucking in light, ethereal purple glow.` },
      { id: "a-l-blade", name: "Foice da Alma", type: ItemType.OFFHAND, rarity: Rarity.LEGENDARY, prompt: `${BASE_PROMPT} A small scythe-like blade, glowing blue soul energy, bone handle.` },
      { id: "a-l-amulet", name: "Olho do Vazio", type: ItemType.AMULET, rarity: Rarity.LEGENDARY, prompt: `${BASE_PROMPT} ${AMULET_POSE} A pendant containing a small black hole, sucking in all light, glowing with purple void energy.` },
      { id: "a-l-ring", name: "Anel da Sombra", type: ItemType.RING, rarity: Rarity.LEGENDARY, prompt: `${BASE_PROMPT} A ring that is invisible to the naked eye, only visible as a distortion in space, glowing with purple energy.` },
      { id: "a-l-gloves", name: "Toque da Morte", type: ItemType.GLOVES, rarity: Rarity.LEGENDARY, prompt: `${BASE_PROMPT} ${GLOVES_POSE} Gloves made of pure shadow, fingers seem to dissolve into smoke, glowing with blue soul energy.` },
      { id: "a-l-pants", name: "Calças do Abismo", type: ItemType.PANTS, rarity: Rarity.LEGENDARY, prompt: `${BASE_PROMPT} ${PANTS_POSE} Trousers made of pure void energy, leaving trails of darkness, glowing purple runes.` },
    ],
  },
};
